#!/bin/bash


#change the following to "false" to disable changing the default server name and motd
setserver="true"
#change the following to "false" to disable updating of server jars and website
syncweb="true"
syncjars="true"
#server name and motd -- DO NOT USE BACKTICKS (`) within it!! -- stuff WONT work if you DO!! ALSO do not use "${anything}" UNLESS YOU KNOW WHAT YOU ARE DOING!!
srvname="Your Minecraft Server"
srvmotd="Minecraft Server"


#DANGER!! setting the following to "true" will redownload the bukkit server! only change if you know what you are doing!
emergbukkit="false"



#~#       this code was smashed together by ayunami2000       #~#

eagurl="https://raw.githubusercontent.com/LAX1DUDE/eaglercraft/main/stable-download/stable-download_repl.zip"

echo ensuring old server process is truly closed...
nginx -s stop -c ~/$REPL_SLUG/nginx.conf -g 'daemon off; pid /tmp/nginx/nginx.pid;' -p /tmp/nginx -e /tmp/nginx/error.log
pkill java
pkill nginx
